[theme]
# Change primary button color used for interactive elements, notably buttons, sliders (green)
primaryColor = "#4CAF50"
# Sets overall background of main content area of app where charts are displayed - dark blue  
backgroundColor = "#00172B"  
# Controls background color of sidebar - light grey
secondaryBackgroundColor = "#E0E0E0"
# Changes color of text in Streamlit app - white  
textColor = "#FFF"  
# Available options: sans serif, serif, monospace
font = "sans serif"  
